// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// survtab
NumericVector survtab(NumericMatrix Xr, int n, int t, NumericVector C, NumericVector U, bool display_progress);
RcppExport SEXP _wcep_survtab(SEXP XrSEXP, SEXP nSEXP, SEXP tSEXP, SEXP CSEXP, SEXP USEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type U(USEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(survtab(Xr, n, t, C, U, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// varvec
NumericVector varvec(NumericVector W, NumericVector uj, NumericMatrix pj, NumericMatrix s_table_c, IntegerVector censor_times, IntegerVector n_riskset, int n, int max_time, bool display_progress);
RcppExport SEXP _wcep_varvec(SEXP WSEXP, SEXP ujSEXP, SEXP pjSEXP, SEXP s_table_cSEXP, SEXP censor_timesSEXP, SEXP n_risksetSEXP, SEXP nSEXP, SEXP max_timeSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type uj(ujSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pj(pjSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type s_table_c(s_table_cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type censor_times(censor_timesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_riskset(n_risksetSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(varvec(W, uj, pj, s_table_c, censor_times, n_riskset, n, max_time, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wcep_survtab", (DL_FUNC) &_wcep_survtab, 6},
    {"_wcep_varvec", (DL_FUNC) &_wcep_varvec, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_wcep(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
