# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

survtab <- function(Xr, n, t, C, U, display_progress = TRUE) {
    .Call('_wcep_survtab', PACKAGE = 'wcep', Xr, n, t, C, U, display_progress)
}

varvec <- function(W, uj, pj, s_table, censor_times, n_riskset, n, max_time, display_progress = TRUE) {
    .Call('_wcep_varvec', PACKAGE = 'wcep', W, uj, pj, s_table, censor_times, n_riskset, n, max_time, display_progress)
}

